# Generated by Django 5.2.3 on 2025-07-06 09:18

from django.db import migrations
   
  
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='telephone',
            new_name='phone',
        ),
    ]
