# Generated by Django 5.2.3 on 2025-07-06 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_telephone_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.PositiveIntegerField(blank=True, null=True)),
                ('car_color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('driver_license', models.ImageField(blank=True, null=True, upload_to='uploads/licenses/')),
                ('gh_card_front', models.ImageField(blank=True, null=True, upload_to='uploads/ghcard_front/')),
                ('gh_card_back', models.ImageField(blank=True, null=True, upload_to='uploads/ghcard_back/')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='uploads/car_photos/')),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('luggage_space', models.CharField(choices=[('small', 'Small bags only'), ('medium', 'Medium luggage (1 per passenger)'), ('large', 'Large luggage possible')], max_length=50)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_post', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
