# Generated by Django 5.2.3 on 2025-07-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_my_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='my_rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.my_booking')),
            ],
        ),
    ]
