# Generated by Django 5.2.3 on 2025-07-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_my_booking_status_my_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_rides',
            name='myride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ridepost'),
            preserve_default=False,
        ),
    ]
