# Generated by Django 5.2.3 on 2025-07-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_my_rides_myride'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_rides',
        ),
    ]
