# Generated by Django 5.2.3 on 2025-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_my_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepost',
            name='ride_status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
