# Generated by Django 5.2.3 on 2025-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ridepost_ride_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ridepost',
            index=models.Index(fields=['departure'], name='app_ridepos_departu_92cd62_idx'),
        ),
        migrations.AddIndex(
            model_name='ridepost',
            index=models.Index(fields=['destination'], name='app_ridepos_destina_2ae9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='ridepost',
            index=models.Index(fields=['departure_date'], name='app_ridepos_departu_618960_idx'),
        ),
        migrations.AddIndex(
            model_name='ridepost',
            index=models.Index(fields=['ride_status', 'allowed_post', 'available_seats'], name='app_ridepos_ride_st_111284_idx'),
        ),
    ]
