# Generated by Django 5.2.3 on 2025-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ridepost_app_ridepos_departu_92cd62_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pic/'),
        ),
    ]
